### ISSUE TITLE
关于学习本软件的知识问题

### ISSUE THREAD

**Issue by scoltzero** [Anapopo/FChinaNet.sh#10]
因为感兴趣，所以想问一下，写出本软件需要具备哪些只是，有没有相应的书籍推荐？目前我知道要具有基础的linux知识和bash的知识，Linux有推荐书籍么？bash呢？你是怎么学习这些的？

**Comment by scoltzero** [comment]
我想着，也能参与你和01sr的研究，能给你们帮帮忙。可我主要写的方向是C语言的嵌入式底层。对这些没什么概念，也是最近才开始了解的。

**Comment by Anapopo** [comment]
搜索引擎、Shell语言、HTTP协议、Linux、不懈求知的心。

**Comment by scoltzero** [comment]
搜索引擎和http协议有教程或者书籍推荐嘛

**Comment by Anapopo** [comment]
大部分从搜索引擎得到的博客中学习。
有一部分开发过程写在 [Wiki](https://github.com/Anapopo/FChinaNet.sh/wiki/FChinaNet-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E) 里了。
