### ISSUE TITLE
小白求支援

### ISSUE THREAD

**Issue by yikexiaoyao** [Anapopo/FChinaNet.sh#4]
小白一枚，现路由器已刷潘多拉，曾用过类似脚本，但是作者不同，用法貌似也不一样，那位大佬目前尚未更新，本人不懂操作，求大佬提供详细操作步骤，非常感激

**Comment by scoltzero** [comment]
我也不会潘多拉哈哈哈，我用的梅林。但是操作应该差不多吧，就是通过软件把脚本先放入路由器目录下面。然后通过webshell 或者其他软件能打开命令行，然后操作啊大概命令就是cd /xxxx
chmod +x /xxxx/verify.sh
sh verify.sh

**Comment by Anapopo** [comment]
步骤大致同 @scoltzero  所说。
简单描述一下：
Windows下用winscp连接路由器，把verify.sh脚本丢进路由器，一般直接`sh verify.sh`就可以运行了。
Linux的话用scp命令传文件过去，然后也是直接运行。

**Comment by yikexiaoyao** [comment]
具体放哪个文件夹如何操作实现开机自启呢，求救，谢谢

**Comment by scoltzero** [comment]
一般丢jffs或者专门放脚本的文件夹，只要不是开机会初始化的文件夹就行，比如梅林的tmp每次开机都会还原的。
至于开机自启，你得问 @Anapopo ,他用的潘多拉。梅林是有自启脚本这个功能的。

**Comment by yikexiaoyao** [comment]
谢谢

**Comment by yikexiaoyao** [comment]
@Anapopo，求教大佬

**Comment by Anapopo** [comment]
@yikexiaoyao 我对Padavan也不是很了解，你可以看看[这个帖子](https://zhuanlan.zhihu.com/p/26766827)

**Comment by yikexiaoyao** [comment]
谢谢
