### ISSUE TITLE
新版无法使用

### ISSUE THREAD

**Issue by z1219176085** [Anapopo/FChinaNet.sh#8]
一直卡在这儿<img src="https://i.loli.net/2018/05/10/5af3fc6e30cd5.png" alt="QQ截图20180510160038.png" title="QQ截图20180510160038.png" />，dalao求助

**Comment by scoltzero** [comment]
1.出现这种问题可能是文件的权限不够，请用WINSCP查看是都有完整的RW权限，并且在运行前，使用语句`chmod +x verify.sh`来赋予权限。
2.请检查路由器配置是否为自动获取动态IP，是否正常连入天翼校园网络。
3.本版本对NTP的兼容性位零，会出现62202的现象，而作者可能被我烦到了，hhh~对我不理不睬，emmmm可能是有事吧，然后我去啃了点linux的书，自己设置设备时间至最近
`date -s 2018-05-10`
就可以了解决出现62202的问题。
 @Anapopo 4.其他问题目前没有发现。。。如果有你只能等作者了。
还有你是openWRT，目前根本就没试验过，目前也就潘多拉和梅林是完美运行的。
你先按照我说的试试看吧。不行再等他。

**Comment by z1219176085** [comment]
在接口更新之前还是能用的
<img src="https://i.loli.net/2018/05/10/5af41eb61df13.png" alt="QQ截图20180510182712.png" title="QQ截图20180510182712.png" />
<img src="https://i.loli.net/2018/05/10/5af41eb61e2bb.png" alt="QQ截图20180510182721.png" title="QQ截图20180510182721.png" />
<img src="https://i.loli.net/2018/05/10/5af41eb62cb8d.png" alt="QQ截图20180510182702.png" title="QQ截图20180510182702.png" />

**Comment by z1219176085** [comment]
<img src="https://i.loli.net/2018/05/10/5af4480d9dbff.png" alt="QQ截图20180510212412.png" title="QQ截图20180510212412.png" />

**Comment by Anapopo** [comment]
试试`curl https://www.baidu.com` 你可能已经连上网络了，不信你打开掌上大学看看在线设备。

**Comment by Anapopo** [comment]
试试不联网执行🤔

**Comment by z1219176085** [comment]
不联网执行会卡住🤔

**Comment by Anapopo** [comment]
我的意思是想要找出不联网卡住的原因，由于不知道你的情况，所以需要逐个排查。
其中的一步是 `curl -svSkI http://test.f-young.cn` ，我想看看有什么输出。😜

**Comment by z1219176085** [comment]
emmmm，我不联网运行了2分钟左右，啥反应都没有，没有输出什么🤔

**Comment by z1219176085** [comment]
emmmm，换了个软件，有输出了
<img src="https://i.loli.net/2018/05/10/5af465c0a247e.jpg" alt="Screenshot_20180510-233021.jpg" title="Screenshot_20180510-233021.jpg" />

**Comment by Anapopo** [comment]
emmmm🙄
