### ISSUE TITLE
5.12

### ISSUE THREAD

**Issue by scoltzero** [Anapopo/FChinaNet.sh#9]

**Comment by scoltzero** [comment]
需要更新，已经失效

**Comment by scoltzero** [comment]
@Anapopo 需要更新，已经失效。
最近电信有毒吧，更新这么频繁。是不是有内奸啊。。。

**Comment by scoltzero** [comment]
@Anapopo 需要更新，已经失效
最近电信有毒啊，更新这么频繁。有内奸吧。。。

**Comment by z1219176085** [comment]
辣鸡电信真坑

**Comment by z1219176085** [comment]
作者加油
<img src="https://i.loli.net/2018/05/12/5af671942df0a.jpg" alt="QQ图片20180512124602.jpg" title="QQ图片20180512124602.jpg" />

**Comment by scoltzero** [comment]
加油

**Comment by Anapopo** [comment]
@scoltzero @z1219176085 已更新各位

**Comment by z1219176085** [comment]
太感谢了😀
